language: php

php:
        - "5.4"
        - "5.5"
        - "5.6"

script: "./tests/run-test.sh"

before_script:
        - composer self-update
        - composer install --prefer-source
        - mysql -u root < ./tests/data/database.sql
