language: php

php:
        - "5.4"
        - "5.5"
        - "5.6"

script: "./tests/run-test.sh"

env:
        - DB=mysql
        - DB=pgsql
        - DB=sqlite

before_script:
        - composer self-update
        - composer install --prefer-source
        - mysql -e 'create database doctrime_mptt_test;'
        - psql -c 'create database doctrime_mptt_test;' -U postgres
        - rm ./tests/data/config.neon
        - cp ./tests/data/config.travis.$DB.neon ./tests/data/config.neon
        - echo $DB

after_failure:
        - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
