language: php

php:
        - "5.4"
        - "5.5"
        - "5.6"

script: "./tests/run-test.sh"

env:
        - DB=mysql
        - DB=pgsql
        - DB=sqlite

before_script:
        - composer self-update
        - composer install --prefer-source
        - mysql -u root < ./tests/data/database.sql
        - rm ./tests/data/config.neon
        - cp ./tests/data/config.travis.$DB.neon ./tests/data/config.neon
        - echo $DB
